name: vpnapp
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.2.0
  phosphor_flutter: ^2.0.0
  convex_bottom_bar: ^3.0.0


  cupertino_icons: ^1.0.8
  transparent_image: ^2.0.1
  firebase_auth: ^5.6.1
  firebase_core: ^3.15.0
  email_validator: ^3.0.0
  lucide_icons: ^0.257.0
  riverpod: ^2.6.1
  animated_text_kit: ^4.2.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  image_picker: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_riverpod: ^2.5.1 
  flutter_native_splash: ^2.4.0

  
  flutter_launcher_icons: ^0.13.1  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/internet-security_11078824.png" 

flutter:
  uses-material-design: true
  assets:
    - assets/countries/brazil.svg
    - assets/countries/canada.svg
    - assets/countries/england.svg
    - assets/countries/France.svg
    - assets/countries/germany.svg
    - assets/countries/italy.svg
    - assets/countries/Netherlands.svg
    - assets/countries/Turkey.svg
    - assets/countries/usa.svg
    - assets/DISCONNECT/downloadSpeedIcon.svg
    - assets/DISCONNECT/forwardSmall.svg
    - assets/DISCONNECT/globe.svg
    - assets/DISCONNECT/globeSvg.svg
    - assets/DISCONNECT/message.svg
    - assets/DISCONNECT/pin.svg
    - assets/DISCONNECT/smallGlobe.svg
    - assets/DISCONNECT/UploadIcon.svg
    - assets/drawer/emoji-happy.svg
    - assets/drawer/eye.svg
    - assets/drawer/Group.svg
    - assets/drawer/logout.svg
    - assets/drawer/note.svg
    - assets/drawer/setting.svg
    - assets/drawer/user-octagon.svg
    - assets/elseAppbar/category-2.svg
    - assets/elseAppbar/crown.svg
    - assets/images/home-page/appbar/category_trans.svg
    - assets/images/home-page/appbar/category.svg
    - assets/images/home-page/appbar/crown.svg
    - assets/images/login-screen/category-2.svg
    - assets/images/login-screen/crown.svg
    - assets/images/login-screen/dot.svg
    - assets/images/login-screen/forget pass.svg
    - assets/images/login-screen/google.svg
    - assets/images/login-screen/info-circle.svg
    - assets/images/login-screen/info.svg
    - assets/images/login-screen/lines.svg
    - assets/images/login-screen/more.svg
    - assets/images/login-screen/power.svg
    - assets/images/login-screen/Vector.png
    - assets/images/login-screen/VPN app (5) 1 (3).png
    - assets/images/login-screen/VPN app (5) 1.png
    - assets/DISCONNECT/globe.svg
    - assets/DISCONNECT/globeSvg.svg
  fonts:
     - family: gilroy
       fonts:
         - asset: assets/fonts/Gilroy-Light.ttf
     
     - family: gilroyBold
       fonts:
         - asset: assets/fonts/Gilroy-Bold.ttf         
