// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU0rmb7vRbmbcjpCIoZKJ58nmv-6Jdee4',
    appId: '1:266368257016:web:4c403b838fccb44046640d',
    messagingSenderId: '266368257016',
    projectId: 'vpnbackend',
    authDomain: 'vpnbackend.firebaseapp.com',
    storageBucket: 'vpnbackend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_PdgP-neCwj6dDkLdXwHsBHqAx0p8XFQ',
    appId: '1:266368257016:android:e45679b7166da20146640d',
    messagingSenderId: '266368257016',
    projectId: 'vpnbackend',
    storageBucket: 'vpnbackend.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU0rmb7vRbmbcjpCIoZKJ58nmv-6Jdee4',
    appId: '1:266368257016:web:aaf6cd30055c99ef46640d',
    messagingSenderId: '266368257016',
    projectId: 'vpnbackend',
    authDomain: 'vpnbackend.firebaseapp.com',
    storageBucket: 'vpnbackend.firebasestorage.app',
  );
}
